using CartService.API.Contracts;
using CartService.API.Mappers;
using CartService.Business.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.Authorization;

namespace CartService.API.Controllers.V1;

[ApiController]
[Route("api/v1/carts")]
[Authorize(Policy = StorePolicies.CartAccess)]
public sealed class CartController : ControllerBase
{
    private readonly ICartService _cartService;

    public CartController(ICartService cartService)
    {
        _cartService = cartService;
    }


    /// <summary>
    /// Gets cart information by cart key.
    /// </summary>
    /// <param name="cartKey">Unique cart key generated by the client.</param>
    /// <returns>Cart model containing cart key and cart items.</returns>
    [HttpGet("{cartKey}")]
    [ProducesResponseType(typeof(CartResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<CartResponse>> GetCart(string cartKey)
    {
        if (!Guid.TryParse(cartKey, out var cartId))
        {
            return BadRequest("Invalid cart key.");
        }

        var items = await _cartService.GetCartItemsAsync(cartId);

        var response = new CartResponse
        {
            CartKey = cartKey,
            Items = items.Select(CartApiMapper.ToResponse).ToList()
        };

        return Ok(response);
    }

    [HttpPost("{cartKey}/items")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> AddItem(string cartKey, CartItemRequest request)
    {
        if (!Guid.TryParse(cartKey, out var cartId))
        {
            return BadRequest("Invalid cart key.");
        }

        try
        {
            var item = CartApiMapper.ToDomain(request);

            await _cartService.AddItemAsync(cartId, item);

            return Ok();
        }
        catch (ArgumentException ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [HttpDelete("{cartKey}/items/{itemId:int}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> DeleteItem(string cartKey, int itemId)
    {
        if (!Guid.TryParse(cartKey, out var cartId))
        {
            return BadRequest("Invalid cart key.");
        }

        if (itemId <= 0)
        {
            return BadRequest("Invalid item id.");
        }

        await _cartService.RemoveItemAsync(cartId, itemId);

        return Ok();
    }
}
